spring:
  application:
    name: common-utils
  datasource:
    url: jdbc:mysql://localhost:3306/utils?useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&transformedBitIsBoolean=true&allowMultiQueries=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Shanghai
    username: root
    password: lifan1994
  redis:
    host: localhost
    port: 6379

logging:
  level:
    root: info
    com.lezai.samples.*: debug

cache:
  hashMapCacheCfg:
    cacheSize: 2000
  globalCfg:
    localCacheSize: 5000
